# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Abfrage_Benutzername.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Abfrage_Benutzername(object):
    def setupUi(self, Abfrage_Benutzername):
        Abfrage_Benutzername.setObjectName("Abfrage_Benutzername")
        Abfrage_Benutzername.resize(405, 332)
        self.centralwidget = QtWidgets.QWidget(Abfrage_Benutzername)
        self.centralwidget.setObjectName("centralwidget")
        self.wie_heisst_du = QtWidgets.QLabel(self.centralwidget)
        self.wie_heisst_du.setGeometry(QtCore.QRect(40, 60, 151, 21))
        self.wie_heisst_du.setObjectName("wie_heisst_du")
        self.Auswahl_Benutzername = QtWidgets.QComboBox(self.centralwidget)
        self.Auswahl_Benutzername.setGeometry(QtCore.QRect(40, 100, 131, 22))
        self.Auswahl_Benutzername.setObjectName("Auswahl_Benutzername")
        self.button = QtWidgets.QPushButton(self.centralwidget)
        self.button.setGeometry(QtCore.QRect(200, 140, 111, 21))
        self.button.setObjectName("button")
        Abfrage_Benutzername.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Abfrage_Benutzername)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 405, 21))
        self.menubar.setObjectName("menubar")
        Abfrage_Benutzername.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Abfrage_Benutzername)
        self.statusbar.setObjectName("statusbar")
        Abfrage_Benutzername.setStatusBar(self.statusbar)

        self.retranslateUi(Abfrage_Benutzername)
        QtCore.QMetaObject.connectSlotsByName(Abfrage_Benutzername)

    def retranslateUi(self, Abfrage_Benutzername):
        _translate = QtCore.QCoreApplication.translate
        Abfrage_Benutzername.setWindowTitle(_translate("Abfrage_Benutzername", "MainWindow"))
        self.wie_heisst_du.setText(_translate("Abfrage_Benutzername", "Wie lautet Dein Nutzername?"))
        self.button.setText(_translate("Abfrage_Benutzername", "Eiskaffee ausgeben"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Abfrage_Benutzername = QtWidgets.QMainWindow()
    ui = Ui_Abfrage_Benutzername()
    ui.setupUi(Abfrage_Benutzername)
    Abfrage_Benutzername.show()
    sys.exit(app.exec_())
