# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Eiskaffee_front_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

# Einstellung des Fensters
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.Ausgabe_Button = QtWidgets.QPushButton(self.centralwidget)
        self.Ausgabe_Button.setGeometry(QtCore.QRect(300, 340, 141, 61))
        self.Ausgabe_Button.setObjectName("Ausgabe_Button")
        self.Ausgabe_Button.setStyleSheet("background-color: rgb(250, 0, 0);")

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        MainWindow.setStyleSheet("background-color: rgb(197, 141, 92);")
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        # Verbindung der clicked-Methode mit dem Signal des Buttons
        self.Ausgabe_Button.clicked.connect(self.clicked)



    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Ausgabe_Button.setText(_translate("MainWindow", "Eiskaffee ausgeben"))

    def clicked(self,):                 # Hier werden die Funktionen der einzelnen
        # Ändern Sie die Hintergrundfarbe des Buttons
        self.Ausgabe_Button.setStyleSheet("background-color: yellow;")

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
