# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Nutzerfenster.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Nutzerfenster(object):
    def setupUi(self, Nutzerfenster):
        Nutzerfenster.setObjectName("Nutzerfenster")
        Nutzerfenster.resize(800, 800)
        self.label = QtWidgets.QLabel(Nutzerfenster)
        self.label.setGeometry(QtCore.QRect(0, 0, 800, 800))
        self.label.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Nutzerfenster)
        self.label_2.setGeometry(QtCore.QRect(20, 20, 51, 71))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("../img/iFridge_klein.png"))
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(Nutzerfenster)
        self.pushButton.setGeometry(QtCore.QRect(50, 600, 111, 71))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Nutzerfenster)
        QtCore.QMetaObject.connectSlotsByName(Nutzerfenster)

    def retranslateUi(self, Nutzerfenster):
        _translate = QtCore.QCoreApplication.translate
        Nutzerfenster.setWindowTitle(_translate("Nutzerfenster", "iFridge"))
        self.pushButton.setText(_translate("Nutzerfenster", "Nutzer_1"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Nutzerfenster = QtWidgets.QWidget()
    ui = Ui_Nutzerfenster()
    ui.setupUi(Nutzerfenster)
    Nutzerfenster.show()
    sys.exit(app.exec_())
