# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ProduktauswahlGUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
#from PySide6 import QtCore, QtGui, QtWidgets


class Ui_Produktauswahl(object):

    # durch Qt5 erstellt
    def setupUi(self, Produktauswahl):
        Produktauswahl.setObjectName("Produktauswahl")
        Produktauswahl.resize(811, 515)
        Produktauswahl.setWindowTitle("Produktauswahl")
        self.centralwidget = QtWidgets.QWidget(Produktauswahl)
        self.centralwidget.setObjectName("centralwidget")
        self.listView = QtWidgets.QListView(self.centralwidget)
        self.listView.setGeometry(QtCore.QRect(20, 50, 371, 391))
        self.listView.setObjectName("listView")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 10, 271, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 460, 381, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(410, 10, 20, 521))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(600, 170, 181, 31))
        self.comboBox.setObjectName("comboBox")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(440, 170, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(440, 250, 361, 41))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(QtGui.QFont.Weight.Normal)

        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(600, 220, 241, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        Produktauswahl.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Produktauswahl)
        self.statusbar.setObjectName("statusbar")
        Produktauswahl.setStatusBar(self.statusbar)


        # Kontostand aktualisieren, wenn ein Nutzer ausgewählt wird
        #self.comboBox.currentIndexChanged.connect(self.update_balance)



        self.retranslateUi(Produktauswahl)
        QtCore.QMetaObject.connectSlotsByName(Produktauswahl)




    def retranslateUi(self, Produktauswahl):
        _translate = QtCore.QCoreApplication.translate
        self.label.setText(_translate("Produktauswahl", "Verfügbare Produkte:"))
        self.label_2.setText(_translate("Produktauswahl", "Aktion: Jedes Produkt kostet aktuell 2,50€!"))
        self.label_3.setText(_translate("Produktauswahl", "Mitarbeiter:"))
        self.pushButton.setText(_translate("Produktauswahl", "Eine Einheit des ausgewählten Produktes kaufen!"))
        self.label_4.setText(_translate("Produktauswahl", "Guthaben:"))







# von Qt5 erstellt
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Produktauswahl = QtWidgets.QMainWindow()
    ui = Ui_Produktauswahl()
    ui.setupUi(Produktauswahl)
    Produktauswahl.show()
    sys.exit(app.exec_())
