# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RGB_Einstellungen.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
from PyQt5 import QtWidgets, uic
from PyQt5.QtGui import QColor
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(800, 800)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(0, 0, 801, 801))
        self.label.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../img/iFridge_klein.png"))
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label.setObjectName("label")
        self.Slider_rot1 = QtWidgets.QSlider(Form)
        self.Slider_rot1.setGeometry(QtCore.QRect(40, 260, 61, 391))
        self.Slider_rot1.setMaximum(255)
        self.Slider_rot1.setSingleStep(5)
        self.Slider_rot1.setOrientation(QtCore.Qt.Vertical)
        self.Slider_rot1.setObjectName("Slider_rot1")
        self.Slider_gruen1 = QtWidgets.QSlider(Form)
        self.Slider_gruen1.setGeometry(QtCore.QRect(120, 260, 61, 391))
        self.Slider_gruen1.setMaximum(255)
        self.Slider_gruen1.setSingleStep(5)
        self.Slider_gruen1.setOrientation(QtCore.Qt.Vertical)
        self.Slider_gruen1.setObjectName("Slider_gruen1")
        self.Slider_blau1 = QtWidgets.QSlider(Form)
        self.Slider_blau1.setGeometry(QtCore.QRect(200, 260, 61, 391))
        self.Slider_blau1.setMaximum(255)
        self.Slider_blau1.setSingleStep(5)
        self.Slider_blau1.setOrientation(QtCore.Qt.Vertical)
        self.Slider_blau1.setObjectName("Slider_blau1")
        self.Slider_gruen2 = QtWidgets.QSlider(Form)
        self.Slider_gruen2.setGeometry(QtCore.QRect(580, 260, 61, 391))
        self.Slider_gruen2.setMaximum(255)
        self.Slider_gruen2.setSingleStep(5)
        self.Slider_gruen2.setOrientation(QtCore.Qt.Vertical)
        self.Slider_gruen2.setObjectName("Slider_gruen2")
        self.Slider_blau2 = QtWidgets.QSlider(Form)
        self.Slider_blau2.setGeometry(QtCore.QRect(660, 260, 61, 391))
        self.Slider_blau2.setMaximum(255)
        self.Slider_blau2.setSingleStep(5)
        self.Slider_blau2.setOrientation(QtCore.Qt.Vertical)
        self.Slider_blau2.setObjectName("Slider_blau2")
        self.Slider_rot2 = QtWidgets.QSlider(Form)
        self.Slider_rot2.setGeometry(QtCore.QRect(500, 260, 61, 391))
        self.Slider_rot2.setMaximum(255)
        self.Slider_rot2.setSingleStep(5)
        self.Slider_rot2.setOrientation(QtCore.Qt.Vertical)
        self.Slider_rot2.setObjectName("Slider_rot2")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(250, 60, 261, 20))
        self.label_2.setStyleSheet("font: 9pt \"Terminal\";\n"
"font: 12pt \"Terminal\";")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(60, 160, 171, 16))
        self.label_3.setStyleSheet("font: 12pt \"Terminal\";")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(530, 160, 171, 16))
        self.label_4.setStyleSheet("font: 12pt \"Terminal\";")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(50, 220, 47, 21))
        self.label_5.setStyleSheet("font: 15pt \"Terminal\";")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(130, 220, 47, 21))
        self.label_6.setStyleSheet("font: 15pt \"Terminal\";")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(210, 220, 47, 21))
        self.label_7.setStyleSheet("font: 15pt \"Terminal\";")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setGeometry(QtCore.QRect(510, 220, 47, 21))
        self.label_8.setStyleSheet("font: 15pt \"Terminal\";")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setGeometry(QtCore.QRect(670, 220, 47, 21))
        self.label_9.setStyleSheet("font: 15pt \"Terminal\";")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(Form)
        self.label_10.setGeometry(QtCore.QRect(590, 220, 47, 21))
        self.label_10.setStyleSheet("font: 15pt \"Terminal\";")
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.labelColor1 = QtWidgets.QLabel(Form)
        self.labelColor1.setGeometry(QtCore.QRect(20, 710, 131, 31))
        self.labelColor1.setStyleSheet("font: 75 12pt \"Terminal\";")
        self.labelColor1.setObjectName("labelColor1")
        self.labelColor2 = QtWidgets.QLabel(Form)
        self.labelColor2.setGeometry(QtCore.QRect(480, 710, 131, 31))
        self.labelColor2.setStyleSheet("font: 75 12pt \"Terminal\";")
        self.labelColor2.setObjectName("labelColor2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "iFridge"))
        self.label_2.setText(_translate("Form", "RGB Einstellungen"))
        self.label_3.setText(_translate("Form", "Innenraum"))
        self.label_4.setText(_translate("Form", "RGB-Leiste"))
        self.label_5.setText(_translate("Form", "rot"))
        self.label_6.setText(_translate("Form", "gruen"))
        self.label_7.setText(_translate("Form", "blau"))
        self.label_8.setText(_translate("Form", "rot"))
        self.label_9.setText(_translate("Form", "blau"))
        self.label_10.setText(_translate("Form", "gruen"))
        self.labelColor1.setText(_translate("Form", "Mischung: "))
        self.labelColor2.setText(_translate("Form", "Mischung: "))


class RGBSlider(QtWidgets.QWidget):
    def __init__(self):
        super(RGBSlider, self).__init__()
        uic.loadUi('RGB_Einstellungen.ui', self)

        # Verbinde die Slider mit der updateColor Methode
        self.Slider_rot1.valueChanged.connect(self.updateColor)
        self.Slider_gruen1.valueChanged.connect(self.updateColor)
        self.Slider_blau1.valueChanged.connect(self.updateColor)

        self.Slider_rot2.valueChanged.connect(self.updateColor)
        self.Slider_gruen2.valueChanged.connect(self.updateColor)
        self.Slider_blau2.valueChanged.connect(self.updateColor)

        # Initiale Farbanzeige
        self.updateColor()

    def updateColor(self):
        red1 = self.Slider_rot1.value()
        green1 = self.Slider_gruen1.value()
        blue1 = self.Slider_blau1.value()

        red2 = self.Slider_rot2.value()
        green2 = self.Slider_gruen2.value()
        blue2 = self.Slider_blau2.value()

        color1 = QColor(red1, green1, blue1)
        colorString1 = color1.name()

        color2 = QColor(red2, green2, blue2)
        colorString2 = color2.name()

        self.labelColor1.setStyleSheet(f"background-color: {colorString1};  color: white;  padding: 10px;  border-radius: 15px;")
        self.labelColor2.setStyleSheet(f"background-color: {colorString2};  color: white;  padding: 10px;  border-radius: 15px;")

if __name__ == '__main__':
    app = QtWidgets.QApplication(sys.argv)
    window = RGBSlider()
    window.show()
    sys.exit(app.exec_())



