# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'Usermanagement.ui'
##
## Created by: Qt User Interface Compiler version 6.7.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QDialog, QDoubleSpinBox,
    QFrame, QLabel, QLineEdit, QListView,
    QPushButton, QSizePolicy, QWidget)

class Ui_Usermanagement(object):
    def setupUi(self, Usermanagement):
        if not Usermanagement.objectName():
            Usermanagement.setObjectName(u"Usermanagement")
        Usermanagement.resize(573, 476)
        Usermanagement.setWindowTitle(u"Nutzerverwaltung")
        self.listView = QListView(Usermanagement)
        self.listView.setObjectName(u"listView")
        self.listView.setGeometry(QRect(20, 50, 191, 391))
        self.listView.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOn)
        self.listView.setHorizontalScrollBarPolicy(Qt.ScrollBarAsNeeded)
        self.label = QLabel(Usermanagement)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(60, 10, 171, 31))
        font = QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label_Nutzeranzahl = QLabel(Usermanagement)
        self.label_Nutzeranzahl.setObjectName(u"label_Nutzeranzahl")
        self.label_Nutzeranzahl.setGeometry(QRect(20, 450, 161, 16))
        font1 = QFont()
        font1.setPointSize(10)
        self.label_Nutzeranzahl.setFont(font1)
        self.pushButton_AddUser = QPushButton(Usermanagement)
        self.pushButton_AddUser.setObjectName(u"pushButton_AddUser")
        self.pushButton_AddUser.setGeometry(QRect(480, 60, 81, 21))
        self.pushButton_RemoveUser = QPushButton(Usermanagement)
        self.pushButton_RemoveUser.setObjectName(u"pushButton_RemoveUser")
        self.pushButton_RemoveUser.setGeometry(QRect(450, 440, 121, 31))
        font2 = QFont()
        font2.setBold(True)
        self.pushButton_RemoveUser.setFont(font2)
        self.line = QFrame(Usermanagement)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(205, 10, 31, 451))
        self.line.setFrameShape(QFrame.Shape.VLine)
        self.line.setFrameShadow(QFrame.Shadow.Sunken)
        self.lineEdit = QLineEdit(Usermanagement)
        self.lineEdit.setObjectName(u"lineEdit")
        self.lineEdit.setGeometry(QRect(300, 60, 151, 20))
        self.label_3 = QLabel(Usermanagement)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(230, 60, 81, 16))
        self.label_3.setFont(font1)
        self.comboBox = QComboBox(Usermanagement)
        self.comboBox.setObjectName(u"comboBox")
        self.comboBox.setGeometry(QRect(300, 150, 191, 22))
        self.comboBox.setEditable(False)
        self.line_2 = QFrame(Usermanagement)
        self.line_2.setObjectName(u"line_2")
        self.line_2.setGeometry(QRect(220, 110, 91, 16))
        self.line_2.setFrameShape(QFrame.Shape.HLine)
        self.line_2.setFrameShadow(QFrame.Shadow.Sunken)
        self.pushButton_deposit = QPushButton(Usermanagement)
        self.pushButton_deposit.setObjectName(u"pushButton_deposit")
        self.pushButton_deposit.setGeometry(QRect(430, 230, 141, 31))
        self.label_2 = QLabel(Usermanagement)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(320, 100, 171, 31))
        self.label_2.setFont(font1)
        self.label_4 = QLabel(Usermanagement)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(340, 190, 201, 31))
        self.label_4.setFont(font1)
        self.line_3 = QFrame(Usermanagement)
        self.line_3.setObjectName(u"line_3")
        self.line_3.setGeometry(QRect(220, 200, 111, 16))
        self.line_3.setFrameShape(QFrame.Shape.HLine)
        self.line_3.setFrameShadow(QFrame.Shadow.Sunken)
        self.line_4 = QFrame(Usermanagement)
        self.line_4.setObjectName(u"line_4")
        self.line_4.setGeometry(QRect(410, 200, 161, 16))
        self.line_4.setFrameShape(QFrame.Shape.HLine)
        self.line_4.setFrameShadow(QFrame.Shadow.Sunken)
        self.pushButton_newBalance = QPushButton(Usermanagement)
        self.pushButton_newBalance.setObjectName(u"pushButton_newBalance")
        self.pushButton_newBalance.setGeometry(QRect(430, 280, 141, 31))
        self.line_5 = QFrame(Usermanagement)
        self.line_5.setObjectName(u"line_5")
        self.line_5.setGeometry(QRect(460, 110, 111, 20))
        self.line_5.setFrameShape(QFrame.Shape.HLine)
        self.line_5.setFrameShadow(QFrame.Shadow.Sunken)
        self.label_5 = QLabel(Usermanagement)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(320, 20, 201, 16))
        self.label_5.setFont(font1)
        self.line_6 = QFrame(Usermanagement)
        self.line_6.setObjectName(u"line_6")
        self.line_6.setGeometry(QRect(220, 20, 91, 16))
        self.line_6.setFrameShape(QFrame.Shape.HLine)
        self.line_6.setFrameShadow(QFrame.Shadow.Sunken)
        self.line_7 = QFrame(Usermanagement)
        self.line_7.setObjectName(u"line_7")
        self.line_7.setGeometry(QRect(460, 20, 111, 20))
        self.line_7.setFrameShape(QFrame.Shape.HLine)
        self.line_7.setFrameShadow(QFrame.Shadow.Sunken)
        self.label_6 = QLabel(Usermanagement)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(230, 150, 81, 16))
        self.label_6.setFont(font1)
        self.doubleSpinBox_amount = QDoubleSpinBox(Usermanagement)
        self.doubleSpinBox_amount.setObjectName(u"doubleSpinBox_amount")
        self.doubleSpinBox_amount.setGeometry(QRect(300, 250, 81, 31))
        self.doubleSpinBox_amount.setMinimum(0.010000000000000)
        self.doubleSpinBox_amount.setValue(5.000000000000000)
        self.label_7 = QLabel(Usermanagement)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(230, 250, 61, 31))
        self.label_7.setFont(font1)
        self.label_8 = QLabel(Usermanagement)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(480, 260, 51, 20))

        self.retranslateUi(Usermanagement)

        QMetaObject.connectSlotsByName(Usermanagement)
    # setupUi

    def retranslateUi(self, Usermanagement):
        self.label.setText(QCoreApplication.translate("Usermanagement", u"Nutzerliste", None))
        self.label_Nutzeranzahl.setText(QCoreApplication.translate("Usermanagement", u"XX registrierte Nutzer", None))
        self.pushButton_AddUser.setText(QCoreApplication.translate("Usermanagement", u"Hinzuf\u00fcgen", None))
        self.pushButton_RemoveUser.setText(QCoreApplication.translate("Usermanagement", u"Nutzer entfernen", None))
        self.label_3.setText(QCoreApplication.translate("Usermanagement", u"Name:", None))
        self.pushButton_deposit.setText(QCoreApplication.translate("Usermanagement", u"Einzahlen", None))
        self.label_2.setText(QCoreApplication.translate("Usermanagement", u"Nutzer ausw\u00e4hlen", None))
        self.label_4.setText(QCoreApplication.translate("Usermanagement", u"Aktionen", None))
        self.pushButton_newBalance.setText(QCoreApplication.translate("Usermanagement", u"Als Kontostand setzen", None))
        self.label_5.setText(QCoreApplication.translate("Usermanagement", u"Nutzer hinzuf\u00fcgen", None))
        self.label_6.setText(QCoreApplication.translate("Usermanagement", u"Name:", None))
        self.doubleSpinBox_amount.setSuffix(QCoreApplication.translate("Usermanagement", u" \u20ac", None))
        self.label_7.setText(QCoreApplication.translate("Usermanagement", u"Betrag:", None))
        self.label_8.setText(QCoreApplication.translate("Usermanagement", u"- oder -", None))
        pass
    # retranslateUi

